export const colors = {
  themeBackground: '#FAFAFA',
  iconColor: '#333333',
  tagColor: '#D0BFFF',
  iconPink: '#D0BFFF',
  radioColor: '#FFF',
  radioOuterColor: '#D0BFFF',
  spinnerColor: '#D0BFFF',
  orderComplete: '#a594e0',
  orderUncomplete: '#fe0000',
  horizontalLine: '#B8B8B8',
  buttonBackground: '#D0BFFF',
  buttonText: '#FFF',
  textErrorColor: '#FA7751',
  headerBackground: '#FFF',
  headerText: '#2a2a2a',
  fontMainColor: '#212121',
  fontSecondColor: '#949393',
  cartContainer: '#FFF',
  startColor: '#D0BFFF',
  white: '#FFF',
  dimWhite: '#d0d0d0',
  green: '#D0BFFF',
  darkgreen: '#D0BFFF',
  rounded: '#a594e0'
}
