export const PERMISSIONS = [
  { label: 'Admin', code: 'Admin' },
  { label: 'Vendors', code: 'Vendors' },
  { label: 'Stores', code: 'Stores' },
  { label: 'Riders', code: 'Riders' },
  { label: 'Users', code: 'Users' },
  { label: 'Staff', code: 'Staff' },
  { label: 'Configuration', code: 'Configuration' },
  { label: 'Orders', code: 'Orders' },
  { label: 'Coupons', code: 'Coupons' },
  { label: 'Cuisine', code: 'Cuisine' },
  { label: 'Banners', code: 'Banners' },
  { label: 'Tipping', code: 'Tipping' },
  { label: 'Commission Rate', code: 'Commission Rate' },
  { label: 'Withdraw Request', code: 'Withdraw Request' },
  { label: 'Notification', code: 'Notification' },
  { label: 'Zone', code: 'Zone' },
  { label: 'Dispatch', code: 'Dispatch' },
  {label:"Shop Type", code:"Shop Type"}
];
