export const FavouriteRestaurant = `#graphql
query UserFavourite ($latitude:Float,$longitude:Float){
  userFavourite(latitude:$latitude,longitude:$longitude) {
    _id
    orderId
    orderPrefix
    name
    image
    address
    location{coordinates}
    deliveryTime
    minimumOrder
    tax
    isAvailable
    reviewCount
    reviewAverage
    reviewData{
      total
      ratings
      reviews{
        _id
        order{
          user{
            _id
            name
            email
          }
        }
        rating
        description
        createdAt
      }
    }
    categories{
      _id
      title
      foods{
        _id
        title
        image
        description
        subCategory
        variations{
          _id
          title
          price
          discounted
          addons
        }
      }
    }
    options{
      _id
      title
      description
      price
    }
    addons{
      _id
      options
      title
      description
      quantityMinimum
      quantityMaximum
    }
    rating
    openingTimes{
      day
      times{
        startTime
        endTime
      }
    }
   }
}`;
export const restaurant = `#graphql
query Restaurant($id:String){
  restaurant(id:$id){
    _id
    orderId
    orderPrefix
    name
    image
    logo
    address
    location{coordinates}
    deliveryTime
    minimumOrder
    tax
    reviewCount
    reviewData{
      total
      ratings
      reviews{
        _id
        order{
          user{
            _id
            name
            email
          }
        }
        rating
        description
        createdAt
      }
    }
    categories{
      _id
      title
      foods{
        _id
        title
        image
        subCategory
        description
        isOutOfStock
        variations{
          _id
          title
          price
          discounted
          addons

        }
      }
    }
    options{
      _id
      title
      description
      price
    }
    addons{
      _id
      options
      title
      description
      quantityMinimum
      quantityMaximum
    }
    zone{
      _id
      title
      tax
    }
    rating
    isAvailable
    openingTimes{
      day
      times{
        startTime
        endTime
      }
    }
    phone
    restaurantUrl
    cuisines
  }
}`;
