import useEnvVars from '../../environment'

const CustomTheme = () => {
  const { PRIMERY_COLOR, SECONDARY_COLOR, TERTIARY_COLOR } = useEnvVars()
  console.log('XYZ', PRIMERY_COLOR, SECONDARY_COLOR, TERTIARY_COLOR)

  const theme = {
    Pink: {
      black: '#000',
      white: '#FFF',
      radioOuterColor: '#FFF',
      mustard: '#d8d8d874',
      borderColor: '#efefef',
      backgroundColor: 'transparent',
      borderBottomColor: '#DAD6D6',
      primery: SECONDARY_COLOR,
      themeBackground: '#FAFAFA',
      menuBar: '#FFF',
      iconColor: '#333333',
      iconColorPink: PRIMERY_COLOR,
      itemCardColor: '#FFF',
      headerColor: PRIMERY_COLOR,
      tagColor: PRIMERY_COLOR,
      radioColor: PRIMERY_COLOR,
      //radioOuterColor: '#949393',
      startColor: PRIMERY_COLOR,
      startOutlineColor: PRIMERY_COLOR,
      spinnerColor: PRIMERY_COLOR,
      orderComplete: SECONDARY_COLOR,
      orderUncomplete: '#fe0000',
      horizontalLine: '#949393',
      lightHorizontalLine: '#f0f0f0',
      firstHeaderBackground: '#F5F5F5',
      buttonBackground: PRIMERY_COLOR,
      buttonText: '#000',
      buttonBackgroundPink: PRIMERY_COLOR,
      buttonTextPink: '#FFF',
      fontWhite: '#FFF',
      shadowColor: '#2a2a2a',
      cartContainer: '#FFF',
      textErrorColor: '#FA7751',
      headerBackground: TERTIARY_COLOR,
      headerMenuBackground: '#FAFAFA',
      headerText: '#FFF',
      fontMainColor: '#212121',
      fontSecondColor: '#949393',
      titleComponentBackground: 'rgba(39,111,191,0.1)',
      titleComponentText: 'rgba(39,111,191,0.8)',
      titleTextError: '#FFF',
      statusSecondColor: '#5A5858',
      starColor: '#4165b9',
      rippleColor: PRIMERY_COLOR,
      backIcon: '#fff',
      backIconBackground: '#000',
      secondaryText: '#A3A0A0',
      main: SECONDARY_COLOR,
      secondaryBackground: '#ECECEC',
      shadow: '#707070',
      starRating: '#E2C077',
      errorInputBack: '#F7E7E5',
      errorInputBorder: '#DB4A39',
      starRating: '#E2C077',
      inputPlaceHolder: '#F3F4F8',
      transparent: '#00000000',
      customizeOpacityBtn: 'rgba(0, 0, 0, 0.74)',
      deleteButton: '#fe0000',
      backgroundColor2: 'rgba(0, 0, 0, 0.5)',
      hex: '#b0afbc',
      gray: 'grey',
      darkBgFont: '#000',
      btnText: '#000'
    },
    // }),
    Dark: {
      black: '#000',
      white: '#FFF',
      themeBackground: '#000',
      menuBar: '#000',
      iconColor: '#FCFCFC',
      itemCardColor: '#000',
      tagColor: PRIMERY_COLOR,
      iconColorPink: PRIMERY_COLOR,
      radioColor: PRIMERY_COLOR,
      radioOuterColor: '#383737',
      startColor: PRIMERY_COLOR,
      startOutlineColor: PRIMERY_COLOR,
      spinnerColor: PRIMERY_COLOR,
      orderComplete: '#1DB20D',
      orderUncomplete: '#fe0000',
      horizontalLine: '#DFDCDC',
      lightHorizontalLine: '#2D2929',
      shadowColor: '#898989',
      cartContainer: '#383737',
      textErrorColor: '#FA7751',
      buttonBackground: '#E8E8E8',
      buttonText: '#000',
      buttonBackgroundPink: PRIMERY_COLOR,
      buttonTextPink: '#FFF',
      fontWhite: '#FFF',
      fontMainColor: '#F9F9F9',
      fontSecondColor: '#7F7F7F',
      headerBackground: '#000',
      headerMenuBackground: '#000',
      headerText: '#FFF',
      colorPrimary300: '#333333',
      titleComponentBackground: 'rgba(39,111,191,0.1)',
      titleComponentText: 'rgba(39,111,191,0.8)',
      titleTextError: '#FFF',
      statusSecondColor: '#949393',
      rippleColor: PRIMERY_COLOR,
      backIcon: '#fff',
      backIconBackground: '#000',
      secondaryText: '#A3A0A0',
      main: SECONDARY_COLOR,
      secondaryBackground: '#ECECEC',
      shadow: '#707070',
      errorInputBack: '#F7E7E5',
      errorInputBorder: '#DB4A39',
      inputPlaceHolder: '#F3F4F8',
      transparent: '#ff000080',
      customizeOpacityBtn: 'rgba(0, 0, 0, 0.74)',
      darkBgFont: '#FFF',
      headerColor: '#000',
      btnText: '#FFF'
    }
  }

  return { theme }
}

export default CustomTheme
