export const DAYS = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']
export const ORDER_STATUS_ENUM = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  ASSIGNED: 'ASSIGNED',
  PICKED: 'PICKED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  CANCELLEDBYREST:'CANCELLEDBYREST'
}
export const NOTIFICATION_TYPES = {
  REVIEW_ORDER: 'REVIEW_ORDER'
}

export const FILTER_TYPE = {
  CHECKBOX: 'checkbox',
  RADIO: 'radio'
}
